### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by KTKPython** [jonasp2004/Berichtsheft#10]
add a search funktion

**Comment by Autism2B2B** [comment]
I do not suppose you would even be capable of using one, since you can't even properly use the English language, tho

**Comment by KTKPython** [comment]
> I do not suppose you would even be capable of using one, since you can't even properly use the English language, tho

i am capale of using one
my last englisch lesson was more than two years ago so my englisch grammar is a bit bad at moment

**Comment by jonasp2004** [comment]
## Search function implemented
It is included since commit #16
