### ISSUE TITLE
delete project

### ISSUE THREAD

**Issue by KTKPython** [jonasp2004/Berichtsheft#12]
for elte project it seems to have the standart pop up like the normal windows pop up 
please create one in the style ur app is 
thanks

**Comment by jonasp2004** [comment]
Ok! I will do it after the Lunch break! 😅

**Comment by Autism2B2B** [comment]
For KTKPython it appears as if he is in dire need of some English Lessons (or better yet a lunatic asylum)

**Comment by KTKPython** [comment]
> For KTKPython it appears as if he is in dire need of some English Lessons (or better yet a lunatic asylum)

Ayo my englisch isgood i just dont know some words i needed and i was too lazy to search and i can understand what i wrote there

**Comment by KTKPython** [comment]
if that is your opinion its it. But my englisch is good enough that you could understand it right?

**Comment by Autism2B2B** [comment]
yes yes, very curry, i agree

**Comment by KTKPython** [comment]
where does that comefrom now

**Comment by Autism2B2B** [comment]
your home country

**Comment by jonasp2004** [comment]
🍿

**Comment by KTKPython** [comment]
who are u
i AM THE FUCK NOT FROM INDIA

**Comment by Autism2B2B** [comment]
sure and i live on the moon with my pet dragon

**Comment by KTKPython** [comment]
WHO THE F ARE YOU

**Comment by Autism2B2B** [comment]
![batman-i-am-batman](https://github.com/jonasp2004/Berichtsheft/assets/121153941/f14313f5-5a1e-4cc6-9725-13a73502f0c3)

**Comment by jonasp2004** [comment]
![image](https://github.com/jonasp2004/Berichtsheft/assets/108411785/707d4b81-9717-44b4-b94d-4355e317395a)

**Comment by jonasp2004** [comment]
![image](https://github.com/jonasp2004/Berichtsheft/assets/108411785/5bdd1678-97be-4bcb-a8b2-864f7cc356c7)

**Comment by KTKPython** [comment]
are u a gummifigur?

**Comment by Autism2B2B** [comment]
![200w](https://github.com/jonasp2004/Berichtsheft/assets/121153941/335096ce-f64a-4a0d-8352-fc2888010dd0)
There ya go

**Comment by jonasp2004** [comment]
![C7S](https://github.com/jonasp2004/Berichtsheft/assets/108411785/d3f1b452-f1af-453a-bf98-12dea67682fc)

**Comment by KTKPython** [comment]
> > are u a gummifigur?
> 
> nah, i'm allergic to Latex

yk what im blocking u now 
its getting too annoying

**Comment by Autism2B2B** [comment]
> > > are u a gummifigur?
> > 
> > 
> > nah, i'm allergic to Latex
> 
> yk what im blocking u now its getting too annoying

says the most annoying person on planet earth

**Comment by Autism2B2B** [comment]
you are aware of the fact that github doesn't have such functionality, are ya?

**Comment by KTKPython** [comment]
it has
